### ISSUE TITLE
can't  build in ubuntu 18.04 ?

### ISSUE THREAD

**Issue by flyfire100** [EpyxZ/Allion#1]
src/bignum.h:50:24: error: invalid use of incomplete type ‘BIGNUM {aka struct bignum_st}’
 class CBigNum : public BIGNUM
                        ^~~~~~
In file included from /usr/include/openssl/bn.h:32:0,
                 from src/bignum.h:10,
                 from src/main.h:11,
                 from src/db.h:8,
                 from src/txdb-bdb.cpp:6:
/usr/include/openssl/ossl_typ.h:80:16: note: forward declaration of ‘BIGNUM {aka struct bignum_st}’
 typedef struct bignum_st BIGNUM;
                ^~~~~~~~~
In file included from src/main.h:11:0,
                 from src/db.h:8,
                 from src/txdb-bdb.cpp:6:
src/bignum.h: In constructor ‘CBigNum::CBigNum()’:
src/bignum.h:55:9: error: ‘BN_init’ was not declared in this scope
         BN_init(this);
         ^~~~~~~
src/bignum.h:55:9: note: suggested alternative: ‘BN_print’
         BN_init(this);
         ^~~~~~~
         BN_print
src/bignum.h: In copy constructor ‘CBigNum::CBigNum(const CBigNum&)’:
src/bignum.h:60:9: error: ‘BN_init’ was not declared in this scope
         BN_init(this);
         ^~~~~~~
src/bignum.h:60:9: note: suggested alternative: ‘BN_print’
         BN_init(this);
         ^~~~~~~
         BN_print
src/bignum.h:61:30: error: cannot convert ‘CBigNum*’ to ‘BIGNUM* {aka bignum_st*}’ for argument ‘1’ to ‘BIGNUM* BN_copy(BIGNUM*, const BIGNUM*)’
         if (!BN_copy(this, &b))
                              ^
src/bignum.h:63:31: error: cannot convert ‘CBigNum*’ to ‘BIGNUM* {aka bignum_st*}’ for argument ‘1’ to ‘void BN_clear_free(BIGNUM*)’
             BN_clear_free(this);
                               ^
src/bignum.h: In member function ‘CBigNum& CBigNum::operator=(const CBigNum&)’:
src/bignum.h:70:30: error: cannot convert ‘CBigNum*’ to ‘BIGNUM* {aka bignum_st*}’ for argument ‘1’ to ‘BIGNUM* BN_copy(BIGNUM*, const BIGNUM*)’
         if (!BN_copy(this, &b))
                              ^
src/bignum.h: In destructor ‘CBigNum::~CBigNum()’:
src/bignum.h:77:27: error: cannot convert ‘CBigNum*’ to ‘BIGNUM* {aka bignum_st*}’ for argument ‘1’ to ‘void BN_clear_free(BIGNUM*)’
         BN_clear_free(this);
                           ^
src/bignum.h: In constructor ‘CBigNum::CBigNum(int8_t)’:
src/bignum.h:80:27: error: ‘BN_init’ was not declared in this scope
     CBigNum(int8_t  n)  { BN_init(this); if (n >= 0) setuint32(n); else setint64(n); }
                           ^~~~~~~
src/bignum.h:80:27: note: suggested alternative: ‘BN_print’
     CBigNum(int8_t  n)  { BN_init(this); if (n >= 0) setuint32(n); else setint64(n); }
                           ^~~~~~~
                           BN_print
src/bignum.h: In constructor ‘CBigNum::CBigNum(int16_t)’:
src/bignum.h:81:27: error: ‘BN_init’ was not declared in this scope
     CBigNum(int16_t n)  { BN_init(this); if (n >= 0) setuint32(n); else setint64(n); }
                           ^~~~~~~
src/bignum.h:81:27: note: suggested alternative: ‘BN_print’
     CBigNum(int16_t n)  { BN_init(this); if (n >= 0) setuint32(n); else setint64(n); }
                           ^~~~~~~
                           BN_print
src/bignum.h: In constructor ‘CBigNum::CBigNum(int32_t)’:
src/bignum.h:82:27: error: ‘BN_init’ was not declared in this scope
     CBigNum(int32_t n)  { BN_init(this); if (n >= 0) setuint32(n); else setint64(n); }
                           ^~~~~~~
src/bignum.h:82:27: note: suggested alternative: ‘BN_print’
     CBigNum(int32_t n)  { BN_init(this); if (n >= 0) setuint32(n); else setint64(n); }
                           ^~~~~~~
                           BN_print
src/bignum.h: In constructor ‘CBigNum::CBigNum(int64_t)’:
src/bignum.h:83:27: error: ‘BN_init’ was not declared in this scope
     CBigNum(int64_t n)  { BN_init(this); if (n >= 0) setuint64(n); else setint64(n); }
                           ^~~~~~~
src/bignum.h:83:27: note: suggested alternative: ‘BN_print’
     CBigNum(int64_t n)  { BN_init(this); if (n >= 0) setuint64(n); else setint64(n); }
                           ^~~~~~~
                           BN_print
src/bignum.h: In constructor ‘CBigNum::CBigNum(uint8_t)’:
src/bignum.h:85:27: error: ‘BN_init’ was not declared in this scope
     CBigNum(uint8_t  n) { BN_init(this); setuint32(n); }
                           ^~~~~~~
src/bignum.h:85:27: note: suggested alternative: ‘BN_print’
     CBigNum(uint8_t  n) { BN_init(this); setuint32(n); }
                           ^~~~~~~
                           BN_print
src/bignum.h: In constructor ‘CBigNum::CBigNum(uint16_t)’:
src/bignum.h:86:27: error: ‘BN_init’ was not declared in this scope
     CBigNum(uint16_t n) { BN_init(this); setuint32(n); }
                           ^~~~~~~
src/bignum.h:86:27: note: suggested alternative: ‘BN_print’
     CBigNum(uint16_t n) { BN_init(this); setuint32(n); }
                           ^~~~~~~
                           BN_print
src/bignum.h: In constructor ‘CBigNum::CBigNum(uint32_t)’:
src/bignum.h:87:27: error: ‘BN_init’ was not declared in this scope
     CBigNum(uint32_t n) { BN_init(this); setuint32(n); }
                           ^~~~~~~
src/bignum.h:87:27: note: suggested alternative: ‘BN_print’
     CBigNum(uint32_t n) { BN_init(this); setuint32(n); }
                           ^~~~~~~
                           BN_print
src/bignum.h: In constructor ‘CBigNum::CBigNum(uint64_t)’:
src/bignum.h:88:27: error: ‘BN_init’ was not declared in this scope
     CBigNum(uint64_t n) { BN_init(this); setuint64(n); }
                           ^~~~~~~
src/bignum.h:88:27: note: suggested alternative: ‘BN_print’
     CBigNum(uint64_t n) { BN_init(this); setuint64(n); }
                           ^~~~~~~
                           BN_print
src/bignum.h: In constructor ‘CBigNum::CBigNum(uint256)’:
src/bignum.h:90:35: error: ‘BN_init’ was not declared in this scope
     explicit CBigNum(uint256 n) { BN_init(this); setuint256(n); }
                                   ^~~~~~~
src/bignum.h:90:35: note: suggested alternative: ‘BN_print’
     explicit CBigNum(uint256 n) { BN_init(this); setuint256(n); }
                                   ^~~~~~~
                                   BN_print
src/bignum.h: In constructor ‘CBigNum::CBigNum(const std::vector<unsigned char>&)’:
src/bignum.h:93:9: error: ‘BN_init’ was not declared in this scope
         BN_init(this);
         ^~~~~~~
src/bignum.h:93:9: note: suggested alternative: ‘BN_print’
         BN_init(this);
         ^~~~~~~
         BN_print
src/bignum.h: In static member function ‘static CBigNum CBigNum::randBignum(const CBigNum&)’:
src/bignum.h:104:39: error: cannot convert ‘CBigNum*’ to ‘BIGNUM* {aka bignum_st*}’ for argument ‘1’ to ‘int BN_rand_range(BIGNUM*, const BIGNUM*)’
         if(!BN_rand_range(&ret, &range)){
                                       ^
src/bignum.h: In static member function ‘static CBigNum CBigNum::RandKBitBigum(uint32_t)’:
src/bignum.h:116:35: error: cannot convert ‘CBigNum*’ to ‘BIGNUM* {aka bignum_st*}’ for argument ‘1’ to ‘int BN_rand(BIGNUM*, int, int, int)’
         if(!BN_rand(&ret, k, -1, 0)){
                                   ^
src/bignum.h: In member function ‘int CBigNum::bitSize() const’:
src/bignum.h:127:33: error: cannot convert ‘const CBigNum*’ to ‘const BIGNUM* {aka const bignum_st*}’ for argument ‘1’ to ‘int BN_num_bits(const BIGNUM*)’
         return  BN_num_bits(this);
                                 ^
src/bignum.h: In member function ‘void CBigNum::setuint32(uint32_t)’:
src/bignum.h:133:33: error: cannot convert ‘CBigNum*’ to ‘BIGNUM* {aka bignum_st*}’ for argument ‘1’ to ‘int BN_set_word(BIGNUM*, long unsigned int)’
         if (!BN_set_word(this, n))
                                 ^
src/bignum.h: In member function ‘uint32_t CBigNum::getuint32() const’:
src/bignum.h:139:32: error: cannot convert ‘const CBigNum*’ to ‘const BIGNUM* {aka const bignum_st*}’ for argument ‘1’ to ‘long unsigned int BN_get_word(const BIGNUM*)’
         return BN_get_word(this);
                                ^
src/bignum.h: In member function ‘int32_t CBigNum::getint32() const’:
src/bignum.h:144:38: error: cannot convert ‘const CBigNum*’ to ‘const BIGNUM* {aka const bignum_st*}’ for argument ‘1’ to ‘long unsigned int BN_get_word(const BIGNUM*)’
         uint64_t n = BN_get_word(this);
                                      ^
src/bignum.h:145:33: error: cannot convert ‘const CBigNum*’ to ‘const BIGNUM* {aka const bignum_st*}’ for argument ‘1’ to ‘int BN_is_negative(const BIGNUM*)’
         if (!BN_is_negative(this))
                                 ^
In file included from src/main.h:11:0,
                 from src/db.h:8,
                 from src/txdb-bdb.cpp:6:
src/bignum.h: In member function ‘void CBigNum::setint64(int64_t)’:
src/bignum.h:191:44: error: cannot convert ‘CBigNum*’ to ‘BIGNUM* {aka bignum_st*}’ for argument ‘3’ to ‘BIGNUM* BN_mpi2bn(const unsigned char*, int, BIGNUM*)’
         BN_mpi2bn(pch, (int)(p - pch), this);
                                            ^
src/bignum.h: In member function ‘uint64_t CBigNum::getuint64()’:
src/bignum.h:196:44: error: cannot convert ‘CBigNum*’ to ‘const BIGNUM* {aka const bignum_st*}’ for argument ‘1’ to ‘int BN_bn2mpi(const BIGNUM*, unsigned char*)’
         size_t nSize = BN_bn2mpi(this, NULL);
                                            ^
src/bignum.h:200:32: error: cannot convert ‘CBigNum*’ to ‘const BIGNUM* {aka const bignum_st*}’ for argument ‘1’ to ‘int BN_bn2mpi(const BIGNUM*, unsigned char*)’
         BN_bn2mpi(this, &vch[0]);
                                ^
src/bignum.h: In member function ‘void CBigNum::setuint64(uint64_t)’:
src/bignum.h:217:47: error: cannot convert ‘CBigNum*’ to ‘BIGNUM* {aka bignum_st*}’ for argument ‘1’ to ‘int BN_set_word(BIGNUM*, long unsigned int)’
             if (!BN_set_word(this, (BN_ULONG)n))
                                               ^
src/bignum.h:244:44: error: cannot convert ‘CBigNum*’ to ‘BIGNUM* {aka bignum_st*}’ for argument ‘3’ to ‘BIGNUM* BN_mpi2bn(const unsigned char*, int, BIGNUM*)’
         BN_mpi2bn(pch, (int)(p - pch), this);
                                            ^
src/bignum.h: In member function ‘void CBigNum::setuint160(uint160)’:
src/bignum.h:272:45: error: cannot convert ‘CBigNum*’ to ‘BIGNUM* {aka bignum_st*}’ for argument ‘3’ to ‘BIGNUM* BN_mpi2bn(const unsigned char*, int, BIGNUM*)’
         BN_mpi2bn(pch, (int) (p - pch), this);
                                             ^
src/bignum.h: In member function ‘uint160 CBigNum::getuint160() const’:
src/bignum.h:277:50: error: cannot convert ‘const CBigNum*’ to ‘const BIGNUM* {aka const bignum_st*}’ for argument ‘1’ to ‘int BN_bn2mpi(const BIGNUM*, unsigned char*)’
         unsigned int nSize = BN_bn2mpi(this, NULL);
                                                  ^
src/bignum.h:281:32: error: cannot convert ‘const CBigNum*’ to ‘const BIGNUM* {aka const bignum_st*}’ for argument ‘1’ to ‘int BN_bn2mpi(const BIGNUM*, unsigned char*)’
         BN_bn2mpi(this, &vch[0]);
                                ^
src/bignum.h: In member function ‘void CBigNum::setuint256(uint256)’:
src/bignum.h:315:45: error: cannot convert ‘CBigNum*’ to ‘BIGNUM* {aka bignum_st*}’ for argument ‘3’ to ‘BIGNUM* BN_mpi2bn(const unsigned char*, int, BIGNUM*)’
         BN_mpi2bn(pch, (int) (p - pch), this);
                                             ^
src/bignum.h: In member function ‘uint256 CBigNum::getuint256() const’:
src/bignum.h:320:50: error: cannot convert ‘const CBigNum*’ to ‘const BIGNUM* {aka const bignum_st*}’ for argument ‘1’ to ‘int BN_bn2mpi(const BIGNUM*, unsigned char*)’
         unsigned int nSize = BN_bn2mpi(this, NULL);
                                                  ^
src/bignum.h:324:32: error: cannot convert ‘const CBigNum*’ to ‘const BIGNUM* {aka const bignum_st*}’ for argument ‘1’ to ‘int BN_bn2mpi(const BIGNUM*, unsigned char*)’
         BN_bn2mpi(this, &vch[0]);
                                ^
src/bignum.h: In member function ‘void CBigNum::setBytes(const std::vector<unsigned char>&)’:
src/bignum.h:335:60: error: cannot convert ‘CBigNum*’ to ‘BIGNUM* {aka bignum_st*}’ for argument ‘3’ to ‘BIGNUM* BN_bin2bn(const unsigned char*, int, BIGNUM*)’
         BN_bin2bn(&vchBytes[0], (int) vchBytes.size(), this);
                                                            ^
In file included from src/bignum.h:10:0,
                 from src/main.h:11,
                 from src/db.h:8,
                 from src/txdb-bdb.cpp:6:
src/bignum.h: In member function ‘std::vector<unsigned char> CBigNum::getBytes() const’:
src/bignum.h:340:22: error: cannot convert ‘const CBigNum*’ to ‘const BIGNUM* {aka const bignum_st*}’ for argument ‘1’ to ‘int BN_num_bits(const BIGNUM*)’
         int nBytes = BN_num_bytes(this);
                      ^
In file included from src/main.h:11:0,
                 from src/db.h:8,
                 from src/txdb-bdb.cpp:6:
src/bignum.h:344:45: error: cannot convert ‘const CBigNum*’ to ‘const BIGNUM* {aka const bignum_st*}’ for argument ‘1’ to ‘int BN_bn2bin(const BIGNUM*, unsigned char*)’
         int n = BN_bn2bin(this, &vchBytes[0]);
                                             ^
src/bignum.h: In member function ‘void CBigNum::setvch(const std::vector<unsigned char>&)’:
src/bignum.h:364:52: error: cannot convert ‘CBigNum*’ to ‘BIGNUM* {aka bignum_st*}’ for argument ‘3’ to ‘BIGNUM* BN_mpi2bn(const unsigned char*, int, BIGNUM*)’
         BN_mpi2bn(&vch2[0], (int) vch2.size(), this);
                                                    ^
src/bignum.h: In member function ‘std::vector<unsigned char> CBigNum::getvch() const’:
src/bignum.h:369:50: error: cannot convert ‘const CBigNum*’ to ‘const BIGNUM* {aka const bignum_st*}’ for argument ‘1’ to ‘int BN_bn2mpi(const BIGNUM*, unsigned char*)’
         unsigned int nSize = BN_bn2mpi(this, NULL);
                                                  ^
src/bignum.h:373:32: error: cannot convert ‘const CBigNum*’ to ‘const BIGNUM* {aka const bignum_st*}’ for argument ‘1’ to ‘int BN_bn2mpi(const BIGNUM*, unsigned char*)’
         BN_bn2mpi(this, &vch[0]);
                                ^
src/bignum.h: In member function ‘CBigNum& CBigNum::SetCompact(uint32_t)’:
src/bignum.h:387:50: error: cannot convert ‘CBigNum*’ to ‘BIGNUM* {aka bignum_st*}’ for argument ‘3’ to ‘BIGNUM* BN_mpi2bn(const unsigned char*, int, BIGNUM*)’
         BN_mpi2bn(&vch[0], (int) vch.size(), this);
                                                  ^
src/bignum.h: In member function ‘uint32_t CBigNum::GetCompact() const’:
src/bignum.h:393:46: error: cannot convert ‘const CBigNum*’ to ‘const BIGNUM* {aka const bignum_st*}’ for argument ‘1’ to ‘int BN_bn2mpi(const BIGNUM*, unsigned char*)’
         uint32_t nSize = BN_bn2mpi(this, NULL);
                                              ^
src/bignum.h:396:32: error: cannot convert ‘const CBigNum*’ to ‘const BIGNUM* {aka const bignum_st*}’ for argument ‘1’ to ‘int BN_bn2mpi(const BIGNUM*, unsigned char*)’
         BN_bn2mpi(this, &vch[0]);
                                ^
src/bignum.h: In member function ‘std::__cxx11::string CBigNum::ToString(int) const’:
src/bignum.h:441:35: error: cannot convert ‘CBigNum*’ to ‘BIGNUM* {aka bignum_st*}’ for argument ‘1’ to ‘void BN_set_negative(BIGNUM*, int)’
         BN_set_negative(&bn, false);
                                   ^
src/bignum.h:444:29: error: cannot convert ‘CBigNum*’ to ‘const BIGNUM* {aka const bignum_st*}’ for argument ‘1’ to ‘int BN_cmp(const BIGNUM*, const BIGNUM*)’
         if (BN_cmp(&bn, &bn0) == 0)
                             ^
src/bignum.h:446:32: error: cannot convert ‘CBigNum*’ to ‘const BIGNUM* {aka const bignum_st*}’ for argument ‘1’ to ‘int BN_cmp(const BIGNUM*, const BIGNUM*)’
         while (BN_cmp(&bn, &bn0) > 0)
                                ^
src/bignum.h:448:54: error: cannot convert ‘CBigNum*’ to ‘BIGNUM* {aka bignum_st*}’ for argument ‘1’ to ‘int BN_div(BIGNUM*, BIGNUM*, const BIGNUM*, const BIGNUM*, BN_CTX*)’
             if (!BN_div(&dv, &rem, &bn, &bnBase, pctx))
                                                      ^
src/bignum.h:454:32: error: cannot convert ‘const CBigNum*’ to ‘const BIGNUM* {aka const bignum_st*}’ for argument ‘1’ to ‘int BN_is_negative(const BIGNUM*)’
         if (BN_is_negative(this))
                                ^
src/bignum.h: In member function ‘CBigNum CBigNum::pow(const CBigNum&) const’:
src/bignum.h:501:41: error: cannot convert ‘CBigNum*’ to ‘BIGNUM* {aka bignum_st*}’ for argument ‘1’ to ‘int BN_exp(BIGNUM*, const BIGNUM*, const BIGNUM*, BN_CTX*)’
         if (!BN_exp(&ret, this, &e, pctx))
                                         ^
src/bignum.h: In member function ‘CBigNum CBigNum::mul_mod(const CBigNum&, const CBigNum&) const’:
src/bignum.h:514:49: error: cannot convert ‘CBigNum*’ to ‘BIGNUM* {aka bignum_st*}’ for argument ‘1’ to ‘int BN_mod_mul(BIGNUM*, const BIGNUM*, const BIGNUM*, const BIGNUM*, BN_CTX*)’
         if (!BN_mod_mul(&ret, this, &b, &m, pctx))
                                                 ^
src/bignum.h: In member function ‘CBigNum CBigNum::pow_mod(const CBigNum&, const CBigNum&) const’:
src/bignum.h:532:56: error: cannot convert ‘CBigNum*’ to ‘BIGNUM* {aka bignum_st*}’ for argument ‘1’ to ‘int BN_mod_exp(BIGNUM*, const BIGNUM*, const BIGNUM*, const BIGNUM*, BN_CTX*)’
             if (!BN_mod_exp(&ret, &inv, &posE, &m, pctx))
                                                        ^
src/bignum.h:535:53: error: cannot convert ‘CBigNum*’ to ‘BIGNUM* {aka bignum_st*}’ for argument ‘1’ to ‘int BN_mod_exp(BIGNUM*, const BIGNUM*, const BIGNUM*, const BIGNUM*, BN_CTX*)’
             if (!BN_mod_exp(&ret, this, &e, &m, pctx))
                                                     ^
src/bignum.h: In member function ‘CBigNum CBigNum::inverse(const CBigNum&) const’:
src/bignum.h:550:49: error: cannot convert ‘CBigNum*’ to ‘BIGNUM* {aka bignum_st*}’ for argument ‘1’ to ‘BIGNUM* BN_mod_inverse(BIGNUM*, const BIGNUM*, const BIGNUM*, BN_CTX*)’
         if (!BN_mod_inverse(&ret, this, &m, pctx))
                                                 ^
src/bignum.h: In static member function ‘static CBigNum CBigNum::generatePrime(unsigned int, bool)’:
src/bignum.h:563:81: error: cannot convert ‘CBigNum*’ to ‘BIGNUM* {aka bignum_st*}’ for argument ‘1’ to ‘int BN_generate_prime_ex(BIGNUM*, int, int, const BIGNUM*, const BIGNUM*, BN_GENCB*)’
      if(!BN_generate_prime_ex(&ret, numBits, (safe == true), NULL, NULL, NULL))
                                                                              ^
src/bignum.h: In member function ‘CBigNum CBigNum::gcd(const CBigNum&) const’:
src/bignum.h:576:41: error: cannot convert ‘CBigNum*’ to ‘BIGNUM* {aka bignum_st*}’ for argument ‘1’ to ‘int BN_gcd(BIGNUM*, const BIGNUM*, const BIGNUM*, BN_CTX*)’
         if (!BN_gcd(&ret, this, &b, pctx))
                                         ^
src/bignum.h: In member function ‘bool CBigNum::isPrime(int) const’:
src/bignum.h:589:61: error: cannot convert ‘const CBigNum*’ to ‘const BIGNUM* {aka const bignum_st*}’ for argument ‘1’ to ‘int BN_is_prime(const BIGNUM*, int, void (*)(int, int, void*), BN_CTX*, void*)’
         int ret = BN_is_prime(this, checks, NULL, pctx, NULL);
                                                             ^
src/bignum.h: In member function ‘bool CBigNum::isOne() const’:
src/bignum.h:597:30: error: cannot convert ‘const CBigNum*’ to ‘const BIGNUM* {aka const bignum_st*}’ for argument ‘1’ to ‘int BN_is_one(const BIGNUM*)’
         return BN_is_one(this);
                              ^
src/bignum.h: In member function ‘bool CBigNum::operator!() const’:
src/bignum.h:603:31: error: cannot convert ‘const CBigNum*’ to ‘const BIGNUM* {aka const bignum_st*}’ for argument ‘1’ to ‘int BN_is_zero(const BIGNUM*)’
         return BN_is_zero(this);
                               ^
src/bignum.h: In member function ‘CBigNum& CBigNum::operator+=(const CBigNum&)’:
src/bignum.h:608:35: error: cannot convert ‘CBigNum*’ to ‘BIGNUM* {aka bignum_st*}’ for argument ‘1’ to ‘int BN_add(BIGNUM*, const BIGNUM*, const BIGNUM*)’
         if (!BN_add(this, this, &b))
                                   ^
src/bignum.h: In member function ‘CBigNum& CBigNum::operator*=(const CBigNum&)’:
src/bignum.h:622:41: error: cannot convert ‘CBigNum*’ to ‘BIGNUM* {aka bignum_st*}’ for argument ‘1’ to ‘int BN_mul(BIGNUM*, const BIGNUM*, const BIGNUM*, BN_CTX*)’
         if (!BN_mul(this, this, &b, pctx))
                                         ^
src/bignum.h: In member function ‘CBigNum& CBigNum::operator<<=(unsigned int)’:
src/bignum.h:641:41: error: cannot convert ‘CBigNum*’ to ‘BIGNUM* {aka bignum_st*}’ for argument ‘1’ to ‘int BN_lshift(BIGNUM*, const BIGNUM*, int)’
         if (!BN_lshift(this, this, shift))
                                         ^
src/bignum.h: In member function ‘CBigNum& CBigNum::operator>>=(unsigned int)’:
src/bignum.h:652:28: error: cannot convert ‘CBigNum*’ to ‘const BIGNUM* {aka const bignum_st*}’ for argument ‘1’ to ‘int BN_cmp(const BIGNUM*, const BIGNUM*)’
         if (BN_cmp(&a, this) > 0)
                            ^
src/bignum.h:658:41: error: cannot convert ‘CBigNum*’ to ‘BIGNUM* {aka bignum_st*}’ for argument ‘1’ to ‘int BN_rshift(BIGNUM*, const BIGNUM*, int)’
         if (!BN_rshift(this, this, shift))
                                         ^
src/bignum.h: In member function ‘CBigNum& CBigNum::operator++()’:
src/bignum.h:667:47: error: cannot convert ‘CBigNum*’ to ‘BIGNUM* {aka bignum_st*}’ for argument ‘1’ to ‘int BN_add(BIGNUM*, const BIGNUM*, const BIGNUM*)’
         if (!BN_add(this, this, BN_value_one()))
                                               ^
src/bignum.h: In member function ‘CBigNum& CBigNum::operator--()’:
src/bignum.h:684:45: error: cannot convert ‘CBigNum*’ to ‘BIGNUM* {aka bignum_st*}’ for argument ‘1’ to ‘int BN_sub(BIGNUM*, const BIGNUM*, const BIGNUM*)’
         if (!BN_sub(&r, this, BN_value_one()))
                                             ^
src/bignum.h: In function ‘const CBigNum operator+(const CBigNum&, const CBigNum&)’:
src/bignum.h:711:27: error: cannot convert ‘CBigNum*’ to ‘BIGNUM* {aka bignum_st*}’ for argument ‘1’ to ‘int BN_add(BIGNUM*, const BIGNUM*, const BIGNUM*)’
     if (!BN_add(&r, &a, &b))
                           ^
src/bignum.h: In function ‘const CBigNum operator-(const CBigNum&, const CBigNum&)’:
src/bignum.h:719:27: error: cannot convert ‘CBigNum*’ to ‘BIGNUM* {aka bignum_st*}’ for argument ‘1’ to ‘int BN_sub(BIGNUM*, const BIGNUM*, const BIGNUM*)’
     if (!BN_sub(&r, &a, &b))
                           ^
src/bignum.h: In function ‘const CBigNum operator-(const CBigNum&)’:
src/bignum.h:727:43: error: cannot convert ‘CBigNum*’ to ‘const BIGNUM* {aka const bignum_st*}’ for argument ‘1’ to ‘int BN_is_negative(const BIGNUM*)’
     BN_set_negative(&r, !BN_is_negative(&r));
                                           ^
src/bignum.h: In function ‘const CBigNum operator*(const CBigNum&, const CBigNum&)’:
src/bignum.h:735:33: error: cannot convert ‘CBigNum*’ to ‘BIGNUM* {aka bignum_st*}’ for argument ‘1’ to ‘int BN_mul(BIGNUM*, const BIGNUM*, const BIGNUM*, BN_CTX*)’
     if (!BN_mul(&r, &a, &b, pctx))
                                 ^
src/bignum.h: In function ‘const CBigNum operator/(const CBigNum&, const CBigNum&)’:
src/bignum.h:744:39: error: cannot convert ‘CBigNum*’ to ‘BIGNUM* {aka bignum_st*}’ for argument ‘1’ to ‘int BN_div(BIGNUM*, BIGNUM*, const BIGNUM*, const BIGNUM*, BN_CTX*)’
     if (!BN_div(&r, NULL, &a, &b, pctx))
                                       ^
src/bignum.h: In function ‘const CBigNum operator%(const CBigNum&, const CBigNum&)’:
src/bignum.h:753:35: error: cannot convert ‘CBigNum*’ to ‘BIGNUM* {aka bignum_st*}’ for argument ‘1’ to ‘int BN_nnmod(BIGNUM*, const BIGNUM*, const BIGNUM*, BN_CTX*)’
     if (!BN_nnmod(&r, &a, &b, pctx))
                                   ^
src/bignum.h: In function ‘const CBigNum operator<<(const CBigNum&, unsigned int)’:
src/bignum.h:761:33: error: cannot convert ‘CBigNum*’ to ‘BIGNUM* {aka bignum_st*}’ for argument ‘1’ to ‘int BN_lshift(BIGNUM*, const BIGNUM*, int)’
     if (!BN_lshift(&r, &a, shift))
                                 ^
src/bignum.h: In function ‘bool operator==(const CBigNum&, const CBigNum&)’:
src/bignum.h:773:83: error: cannot convert ‘const CBigNum*’ to ‘const BIGNUM* {aka const bignum_st*}’ for argument ‘1’ to ‘int BN_cmp(const BIGNUM*, const BIGNUM*)’
 perator==(const CBigNum& a, const CBigNum& b) { return (BN_cmp(&a, &b) == 0); }
                                                                      ^
src/bignum.h: In function ‘bool operator!=(const CBigNum&, const CBigNum&)’:
src/bignum.h:774:83: error: cannot convert ‘const CBigNum*’ to ‘const BIGNUM* {aka const bignum_st*}’ for argument ‘1’ to ‘int BN_cmp(const BIGNUM*, const BIGNUM*)’
 perator!=(const CBigNum& a, const CBigNum& b) { return (BN_cmp(&a, &b) != 0); }
                                                                      ^
src/bignum.h: In function ‘bool operator<=(const CBigNum&, const CBigNum&)’:
src/bignum.h:775:83: error: cannot convert ‘const CBigNum*’ to ‘const BIGNUM* {aka const bignum_st*}’ for argument ‘1’ to ‘int BN_cmp(const BIGNUM*, const BIGNUM*)’
 perator<=(const CBigNum& a, const CBigNum& b) { return (BN_cmp(&a, &b) <= 0); }
                                                                      ^
src/bignum.h: In function ‘bool operator>=(const CBigNum&, const CBigNum&)’:
src/bignum.h:776:83: error: cannot convert ‘const CBigNum*’ to ‘const BIGNUM* {aka const bignum_st*}’ for argument ‘1’ to ‘int BN_cmp(const BIGNUM*, const BIGNUM*)’
 perator>=(const CBigNum& a, const CBigNum& b) { return (BN_cmp(&a, &b) >= 0); }
                                                                      ^
src/bignum.h: In function ‘bool operator<(const CBigNum&, const CBigNum&)’:
src/bignum.h:777:83: error: cannot convert ‘const CBigNum*’ to ‘const BIGNUM* {aka const bignum_st*}’ for argument ‘1’ to ‘int BN_cmp(const BIGNUM*, const BIGNUM*)’
 operator<(const CBigNum& a, const CBigNum& b)  { return (BN_cmp(&a, &b) < 0); }
                                                                       ^
src/bignum.h: In function ‘bool operator>(const CBigNum&, const CBigNum&)’:
src/bignum.h:778:83: error: cannot convert ‘const CBigNum*’ to ‘const BIGNUM* {aka const bignum_st*}’ for argument ‘1’ to ‘int BN_cmp(const BIGNUM*, const BIGNUM*)’
 operator>(const CBigNum& a, const CBigNum& b)  { return (BN_cmp(&a, &b) > 0); }
                                                                       ^
Makefile:6638: recipe for target 'build/txdb-bdb.o' failed
make: *** [build/txdb-bdb.o] Error 1
